
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['WEDDING_DATABASE_HOST'] %>
  # username: postgres
  password:
  database: wedding_development

test:
  <<: *default
  database: wedding_test

production:
  <<: *default
  database: wedding_production
  username: wedding
  password: <%= ENV['WEDDING_DATABASE_PASSWORD'] %>
